---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    type: webapp
    author: intelliqit
spec:
  containers:
   - name: ghost
     image: ghost
     env:
      - name: NODE_ENV
        value: development
     ports:
      - containerPort: 2368 
        hostPort: 8080 
