---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: intelliqit
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
   app: db
   author: intelliqit
...
