---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  clusterIP: None
  ports:
    - port: 3306
      name: web
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: db
spec:
  replicas: 2
  serviceName: mysql
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: mysql-pod
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
              name: web
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: intelliqit
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
       name: mysql-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
...
          
    
