---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    type: appserver
spec:
  containers:
    - name: tomcat
      image: tomee
  tolerations:
    - key: slave2
      operator: Equal
      value: intelliqit2
      effect: NoSchedule
...
